<?php
$id = 1;
$item = $post->getPost($id);

$section = $item[0]['title'];

include __DIR__ . '/header.phtml';
?>
         <section>
            <div class="container">
                 <div class="entry-list single">
                    <article>
                        <h1><?php echo $item[0]['title']; ?></h1>
                        <time datetime="<?php $item[0]['date']; ?>"><?php echo date('F d, Y', strtotime($item[0]['date'])); ?></time>
                        <div class="entry">
                            <p><?php echo $item[0]['body']; ?></p>
                            <p><?php if (!empty($item[0]['tags'])) {
                               $tags = explode(trim(", "), $item[0]['tags']);
                               echo "<ul>";
                               foreach ($tags as $tag) {
                                   echo "<li><a href='/../tags/" . trim($tag) . "'>" . $tag . "</a></li>";
                               }
                               echo "</ul>";
                               }
                               ?></p>
                            <p><a class="link" href="/edit/<?php echo $id; ?>">Edit Entry</a></p>
                            <p><a class="link" href="/delete/<?php echo $id; ?>">Delete Entry</a></p>
                        </div>
                    </article>
                </div>
            </div>
        </section>
        <section class="entry-comments">
            <div class="container">
                    <h2>Comments</h2>
                    <div class="comment">
                        <strong>Carling Kirk</strong>
                        <time datetime="2016-01-31 1:00">January 31, 2016 at 1:00</time>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut rhoncus felis, vel tincidunt neque. Vestibulum ut metus eleifend, malesuada nisl at, scelerisque sapien. Vivamus pharetra massa libero, sed feugiat turpis efficitur at.</p>
                    </div>
                    <div class="new-comment">
                        <form>
                              <label for="name">Name</label>
                              <input type="text" name="name"><br>
                              <label for="comment">Comment</label>
                              <textarea rows="5" name="comment"></textarea>
                              <input type="submit" value="Post Comment" class="button">
                        </form>
                    </div>
            </div>
        </section>
<?php include __DIR__ . '/footer.phtml'; ?>
