<?php
$section = $item[0]['title'];
var_dump($item);

include __DIR__ . '/header.phtml';
?>
         <section>
            <div class="container">
                 <div class="entry-list single">
                    <article>
                        <h1><?php echo $item[0]['title']; ?></h1>
                        <time datetime="<?php $item[0]['date']; ?>"><?php echo date('F d, Y', strtotime($item[0]['date'])); ?></time>
                        <div class="entry">
                            <p><?php echo $item[0]['body']; ?></p>
                            <p><?php if (!empty($item[0]['tags'])) {
                               $tags = explode(trim(", "), $item[0]['tags']);
                               echo "<ul>";
                               foreach ($tags as $tag) {
                                   echo "<li><a href='/../tags?tag=" . trim($tag) . "'>" . $tag . "</a></li>";
                               }
                               echo "</ul>";
                               }
                               ?></p>
                            <p><a class="link" href="/edit/<?php echo $id;  ?>">Edit Entry</a></p>
                            <p><a class="link" href="/delete/<?php echo $id; ?>">Delete Entry</a></p>
                        </div>
                    </article>
                </div>
            </div>
        </section>
        <section class="entry-comments">
            <div class="container">
                    <h2>Comments</h2>
                    <div class="comment">
                        <?php
                        foreach ($comment->getComments($id) as $item) {
                            echo "<strong>" . $item['name'] . "</strong>";
                            echo "<p>" . $item['body'] . "</p>";
                        }
                        ?>
                    </div>
                    <div class="new-comment">
                        <form method="post">
                              <label for="name">Name<span style="color:red">*</span></label>
                              <input type="text" name="name" required><br>
                              <label for="comment">Comment<span style="color:red">*</span></label>
                              <textarea rows="5" name="comment" required></textarea>
                              <input type="submit" value="Post Comment" class="button">
                        </form>
                    </div>
            </div>
        </section>
<?php include __DIR__ . '/footer.phtml'; ?>
