<?php
include __DIR__ . '/../config.php';

$section = "Edit Entry";

if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    $title = trim(filter_input(INPUT_POST, 'title', FILTER_SANITIZE_STRING));
    $date = trim(filter_input(INPUT_POST, 'date', FILTER_SANITIZE_STRING));
    $entry = trim(filter_input(INPUT_POST, 'entry', FILTER_SANITIZE_STRING));
    $tags = trim(filter_input(INPUT_POST, 'tags', FILTER_SANITIZE_STRING));

    $data = [$title, $date, $entry, $tags];

    $post->updatePost($data);
}

include __DIR__ . '/header.phtml';
?>
         <section>
             <div class="container">
                <div class="edit-entry">
                    <h2>Edit Entry</h2>
                    <form method="post" action="/">
                        <label for="title">Title</label>
                        <input type="text" name="title"><br>
                        <label for="date">Date</label>
                        <input type="date" name="date"><br>
                        <label for="entry">Entry</label>
                        <textarea rows="5" name="entry"></textarea>
                        <label for="tags">Tags (separate with commas)</label>
                        <textarea rows="2" name="tags"></textarea>
                        <input type="submit" value="Save Entry" class="button">
                        <a href="index.pthml" class="button button-secondary">Cancel</a>
                    </form>
                </div>
            </div>
        </section>
<?php include __DIR__ . '/footer.phtml'; ?>
