<?php
$section = "Home";

include __DIR__ . '/header.phtml';
?>
         <section>
             <div class="container">
                <div class="entry-list">
                    <article><?php
                    foreach ($post->getPosts() as $item) {
                        echo "<h2><a href='entries/" . $item[implode('-', 'title')] . "'>" . $item['title'] . "</a></h2>";
                        echo "<time datetime='" . $item['date'] . "'>" . date("F d, Y", strtotime($item['date'])) . "</time><br>";
                        if (!empty($item['tags'])) {
                            $tags = explode(trim(', '), $item['tags']);
                            foreach ($tags as $tag) {
                                echo "<a href='tag/" . trim($tag) . "'>" . $tag . "</a><br>";
                            }
                        }
                    }
                    ?>
                    </article>
                </div>
            </div>
        </section>
<?php include __DIR__ . '/footer.phtml'; ?>
