<?php
$title = $date = $entry = $tags = '';

$section = "New Entry";

if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    $title = trim(filter_input(INPUT_POST, 'title', FILTER_SANITIZE_STRING));
    $date = trim(filter_input(INPUT_POST, 'date', FILTER_SANITIZE_STRING));
    $entry = trim(filter_input(INPUT_POST, 'entry', FILTER_SANITIZE_STRING));
    $tags = trim(filter_input(INPUT_POST, 'tags', FILTER_SANITIZE_STRING));

    $post->createPost($title, $date, $entry, $tags);
}

include __DIR__ . '/header.phtml';
?>
         <section>
             <div class="container">
                <div class="new-entry">
                    <h2>Publish New Entry</h2>
                    <form method="post" action="/">
                        <label for="title">Title<span style="color:red">*</span></label>
                        <input type="text" name="title" required><br>
                        <label for="date">Date<span style="color:red">*</span></label>
                        <input type="datetime-local" name="date" required><br>
                        <label for="entry">Entry<span style="color:red">*</span></label>
                        <textarea rows="5" name="entry" required></textarea>
                        <label for="tags">Tags (separate with commas)</label>
                        <textarea rows="2" name="tags"></textarea>
                        <input type="submit" value="Publish Entry" class="button">
                        <a href="/" class="button button-secondary">Cancel</a>
                    </form>
                </div>
            </div>
        </section>
<?php include __DIR__ . '/footer.phtml'; ?>
