<?php
foreach ($items as $item) {
    $section = $item['tags'];
}

include __DIR__ . '/header.phtml';
?>
  <section>
    <div class="container">
      <div class="entry-list">
        <article><?php
        foreach ($items as $item) {
            echo "<h2><a href='/../entries/" . $item['slug'] . "'>" . $item['title'] . "</a></h2>";
            echo "<time datetime='" . $item['date'] . "'>" . date("F d, Y", strtotime($item['date'])) . "</time><br>";
        }
        ?>
        </article>
      </div>
    </div>
  </section>
<?php include __DIR__ . '/footer.phtml'; ?>
